# clock signal
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

#on board slide switches
set_property PACKAGE_PIN J15 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN J15 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

# ON BOARD LED
set_property PACKAGE_PIN H17 [get_ports ]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

# segment display
set_property PACKAGE_PIN J17 [get_ports AN[0]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[0]]
set_property PACKAGE_PIN J18 [get_ports AN[1]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[1]]
set_property PACKAGE_PIN T9 [get_ports AN[2]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[2]]
set_property PACKAGE_PIN J14 [get_ports AN[3]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[3]]
set_property PACKAGE_PIN P14 [get_ports AN[4]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[4]]
set_property PACKAGE_PIN T14 [get_ports AN[5]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[5]]
set_property PACKAGE_PIN K2 [get_ports AN[6]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[6]]
set_property PACKAGE_PIN U13 [get_ports AN[7]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[7]]

set_property PACKAGE_PIN T10 [get_ports A2G[0]]
set_property IOSTANDARD LVCMOS33 [get_ports A2G[0]]
set_property PACKAGE_PIN R10 [get_ports A2G[1]]
set_property IOSTANDARD LVCMOS33 [get_ports A2G[1]]
set_property PACKAGE_PIN K16 [get_ports A2G[2]]
set_property IOSTANDARD LVCMOS33 [get_ports A2G[2]]
set_property PACKAGE_PIN K13 [get_ports A2G[3]]
set_property IOSTANDARD LVCMOS33 [get_ports A2G[3]]
set_property PACKAGE_PIN P15 [get_ports A2G[4]]
set_property IOSTANDARD LVCMOS33 [get_ports A2G[4]]
set_property PACKAGE_PIN T11 [get_ports A2G[5]]
set_property IOSTANDARD LVCMOS33 [get_ports A2G[5]]
set_property PACKAGE_PIN L18 [get_ports A2G[6]]
set_property IOSTANDARD LVCMOS33 [get_ports A2G[6]]